#
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

# profile for installing Hono
# - without monitoring infrastructure
# - with example Infinispan data grid
# - using Quarkus based native images
# - with CoAP adapter only

useLoadBalancer: false

dataGridExample:
  enabled: true

honoImagesType: quarkus-native

adapters:
  amqp:
    enabled: false
  coap:
    enabled: true
  http:
    enabled: false
  mqtt:
    enabled: false
  lora:
    enabled: false
