{{- if and .Values.deviceRegistryExample.enabled ( eq .Values.deviceRegistryExample.type "mongodb" ) }}
#
# Copyright (c) 2020, 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry-conf" }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: 1
      auth:
        {{- if .Values.deviceRegistryExample.hono.auth }}
        {{- .Values.deviceRegistryExample.hono.auth | toYaml | nindent 8 }}
        {{- else }}
        host: {{ printf "%s-service-auth" .Release.Name | quote }}
        port: 5671
        trustStorePath: "/opt/hono/tls/ca.crt"
        hostnameVerificationRequired: false
        name: {{ printf "Hono %s" $args.component | quote }}
        supportedSaslMechanisms: "PLAIN"
        validation:
          certPath: "/opt/hono/config/auth-server-cert.pem"
        connectTimeout: 2000
        {{- end }}
      registry:
        amqp:
          {{- if .Values.deviceRegistryExample.hono.registry.amqp }}
          {{- .Values.deviceRegistryExample.hono.registry.amqp | toYaml | nindent 10 }}
          {{- else }}
          bindAddress: "0.0.0.0"
          keyPath: "/opt/hono/config/key.pem"
          certPath: "/opt/hono/config/cert.pem"
          {{- end }}
        http:
          {{- if .Values.deviceRegistryExample.hono.registry.http }}
          {{- .Values.deviceRegistryExample.hono.registry.http | toYaml | nindent 10 }}
          {{- else }}
          authenticationRequired: false
          bindAddress: "0.0.0.0"
          keyPath: "/opt/hono/config/key.pem"
          certPath: "/opt/hono/config/cert.pem"
          insecurePortEnabled: true
          insecurePortBindAddress: "0.0.0.0"
          {{- end }}
          deviceIdPattern: "^[a-zA-Z0-9-_\\.\\:]+$"
        {{- if .Values.deviceRegistryExample.hono.registry.svc }}
        svc:
          {{- .Values.deviceRegistryExample.hono.registry.svc | toYaml | nindent 10 }}
        {{- end }}
      mongodb:
        {{- if .Values.deviceRegistryExample.mongoDBBasedDeviceRegistry.mongodb}}
        {{- .Values.deviceRegistryExample.mongoDBBasedDeviceRegistry.mongodb | toYaml | nindent 8 }}
        {{- else }}
        host: {{ printf "%s-%s" .Release.Name .Values.mongodb.nameOverride | quote }}
        port: {{ .Values.mongodb.service.port }}
        dbName: {{ first .Values.mongodb.auth.databases | quote }}
        username: {{ first .Values.mongodb.auth.usernames | quote }}
        password: {{ first .Values.mongodb.auth.passwords | quote }}
        {{- end }}
      {{- include "hono.messagingNetworkClientConfig" ( dict "dot" . "component" $args.component "kafkaMessagingSpec" .Values.deviceRegistryExample.hono.kafka ) | nindent 6 }}
    {{- include "hono.quarkusConfig" $args | indent 4 }}
data:
  key.pem: {{ .Files.Get "example/certs/device-registry-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "example/certs/device-registry-cert.pem" | b64enc }}
  auth-server-cert.pem: {{ .Files.Get "example/certs/auth-server-cert.pem" | b64enc }}
{{- end }}
