quarkus:
  log:
    category:
      "org.apache.kafka":
        level: ERROR
      "org.eclipse.hono":
        level: INFO
      "org.eclipse.hono.client.impl.HonoConnectionImpl":
        level: ERROR
